# Site settings
title: Galaxy Training
email:
description: Community Site
baseurl:
url:
twitter_username:
github_username:  gmauro
pages_url: https://gmauro.github.io/Galaxy4Developers
github_url: https://github.com/gmauro/Galaxy4Developers

# Build settings
markdown: kramdown
